### ISSUE TITLE
[Bug]: TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file - When using QwikJS framework

### ISSUE THREAD

**Issue by jmcelreavey** [wallabyjs/console-ninja#130]
### What happened?

When I use QwikJS with Console-Ninja I get the error:
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file

I'm just using an example project

### Version

latest

### Steps to reproduce (or sample repo)

`npm create qwik@latest`
`console-ninja npm run dev`

### Log output

```shell
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at new NodeError (node:internal/errors:399:5)
    at Object.fileURLToPath (node:internal/url:1493:11)
    at ESMLoader.commonjsStrategy (node:internal/modules/esm/translators:151:36)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14) {
  code: 'ERR_INVALID_URL_SCHEME'
}
```

**Comment by NikGovorov** [comment]
We support [Qwik](https://github.com/wallabyjs/console-ninja#supported-technologies) out of the box, you don't need to prefix your `npm run dev` command with `console-ninja`.

**Comment by smcenlly** [comment]
For `QwikJS` projects, you do not launch Console Ninja as a [universal node application](https://github.com/wallabyjs/console-ninja#universal-node-applications), instead because QwikJS is a [built-in supported technology](https://github.com/wallabyjs/console-ninja#supported-technologies), you only need use `npm run dev` after starting VS Code.
