### ISSUE TITLE
[Feature]: Support turbopack in next.js (and standalone in the future)

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/console-ninja#136]
### Describe the feature you'd like.

👋 Hi, long-time fan of the wallaby / quokka and also console ninja recently.

When I play with console ninja bit, it seems like it only works with plain next devserver. If next runs with turbopack (`next dev --turbo`), looks like it doesn't work anymore.

Curious if there's a plan to support turbopack as well.

**Comment by ArtemGovorov** [comment]
Hey @kwonoj 👋 , so nice to see you like Console Ninja too, appreciate you being our user for so many years!

We have investigated a bit and right now it's expected that Console Ninja doesn't work with Turbopack yet.

The reason why is that we intercept file reads on node.js `fs` level to instrument `console.log` calls and feed modified files to a dev server. Turbopack as you know written in Rust and from a brief look it's doing its own fs watch/reads and providing web server, so our options of intercepting file reads, or even file serving to browser, to be able to modify it are very limited (if any).

One way that we could try to integrate with Turbopack is to provide a [loader](https://turbo.build/pack/docs/features/customizing-turbopack). We have tried to provide a loader like this:

```
const nextConfig = {
  ...
  experimental: {
    ..
    turbo: {
        loaders: {
          '.ts': ['./ninjaLoader'],
        },
    },
  },
};
```

and it gets called, but the issue is that Turbopack only runs our loader for all Typescript files then, and doesn't run its built-in Typescript compilation (that it would run without the loader).

Maybe you know if there's a way to tell Turbopack to run a loader for some files and then chain its built-in ones somehow?

Ideally, for a seamless user experience, it would be great if Turbopack provided an extension API to intercept/modify file reads that it's doing. Or if we had to use a loader, it would be ideal to be able insert the loader dynamically somehow without having to modify user's `next.config.js`.

**Comment by kwonoj** [comment]
I think you're correct in pretty much every perspective. Thanks for sharing detail.

I think the main issue is Turbopack does not allow, or exposes hook to its filesystem. More specifically, there are some internal assets turbopack handles which you probably are interested in injecting some codes to devserver, are strictly attempt to not to allow external modification. For those reason, setting a js-side loader may not able to work for your purpose.

Unfortunately not able to confidently say what Turbopack can provide to workaround this at this moment. Described behavior above sounds like somewhat conflicting to the main design of turbpack itself for some aspect. But also it's bit early stage and things may change. Please feel free to close if you'd like to manage issues requires long time from upstream - I can try to file new one if there's something new. Thanks for looking into.

**Comment by JonParton** [comment]
Just to toss in that I also had to debug and find this out myself today as console ninja hadn't been working. 

Shame it can't work with `--turbo` at the moment but understand the challenges! 

Is it worth making sure this is in the docs so people like me don't run around trying to find out why? (Is it concurrently, is it wsl2 etc etc). 

![image](https://github.com/wallabyjs/console-ninja/assets/15039843/806ff292-e1a4-40e7-902a-633531e00649)

May also be worth putting a note in Troubleshooting? 

p.s. looks like Next is getting closer and closer to making turbo the default ... That would be a sad day if there is no answer! ... not sure if the guys writing turbo would engage with you to discuss?

**Comment by kwonoj** [comment]
I forgot I crated this request.

I believe q is answered adequately in https://github.com/wallabyjs/console-ninja/issues/136#issuecomment-1522637639 and turbopack does not have any immediate plan to support 3rd party injection, so closing on my end.

**Comment by smcenlly** [comment]
@JonParton - I have added this issue to address your concern: https://github.com/wallabyjs/console-ninja/issues/292.

**Comment by ArtemGovorov** [comment]
Console Ninja now ships with built-in **Turbopack** support. Fire up a modern Next.js project (where `npm run dev` runs Turbopack by default) and Console Ninja will now seamlessly capture and map your runtime logs, errors and network calls just like it does with webpack builds.
