### ISSUE TITLE
[Bug]: hover-tooltip panel have't icons

### ISSUE THREAD

**Issue by ZhangPan66** [wallabyjs/console-ninja#213]
### What happened?

When I updated the vscode version to 1.83, my hover-tooltip panel only had a "show in Console Output" icon. Or do I have to upgrade to the console ninjia prop version to use the functions of other icons in the hover-tooltip panel?

### Version

1.0.232

### Steps to reproduce (or sample repo)

...

### Log output

```shell
...
```

**Comment by ArtemGovorov** [comment]
> Or do I have to upgrade to the console ninjia prop version to use the functions of other icons in the hover-tooltip panel?

Yes, in order to use [Pro features](https://github.com/wallabyjs/console-ninja#pro-features), including those exposed via additional icons (such as Watchpoints, Highlight, Copy, etc.), Pro feature set needs to be enabled. To enable [Pro features](https://console-ninja.com/pro), you may [purchase Console Ninja subscription](https://account.wallabyjs.com/shop/console-ninja/buy/).

**Comment by ZhangPan66** [comment]
Thanks

**Comment by ZhangPan66** [comment]
@ArtemGovorov  Thanks
