### ISSUE TITLE
[Bug]: Can't find console ninja on vscode extentions

### ISSUE THREAD

**Issue by Ribapax** [wallabyjs/console-ninja#237]
### What happened?

I searched for cosole ninja on the marketplace (online), and found it, when I tried to look for it inside vscode I can't seen to find it

### Version

None

### Steps to reproduce (or sample repo)

I am using linux, a manjaro distribution

### Log output

```shell
I don't have access to the log because I wans't able to even download the extension
```

**Comment by smcenlly** [comment]
It sounds like you may be using `vscodium` and not `vscode`.

Quokka is not available in the [Open VSX registry](https://open-vsx.org) because our licensing model does not allow us to be hosted in their repository.

You will need to download Quokka from [here](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode), and install it using the `Extensions: Install from VSIX...` VS Code command.

**Comment by smcenlly** [comment]
My apologies, I mentioned Quokka instead of Console Ninja in my reply. Updated reply below:

It sounds like you may be using vscodium and not vscode.

Console Ninja is not available in the [Open VSX registry](https://open-vsx.org/) because our licensing model does not allow us to be hosted in their repository.

You will need to download Console Ninja from [here](https://marketplace.visualstudio.com/items?itemName=WallabyJs.console-ninja), and install it using the Extensions: Install from VSIX... VS Code command.
