### ISSUE TITLE
[Bug]: Ninja Artefacts in Committed Source Code

### ISSUE THREAD

**Issue by jcubic** [wallabyjs/console-ninja#297]
### What happened?

There is malware spread over GitHub:

https://github.com/search?q=_consoleNinjaAllowedToStart&type=code

That indicate this is something related to your project. I think you should investiage what is happening. Multiple html pages contain injected and obfuscated payload that contain text "_consoleNinjaAllowedToStart".

### Version

N/A

### CLI command to start your dev tool

N/A

### Steps to reproduce (or sample repo)

N/A

### Log output

```shell
N/A
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. 

This is not malware, nor is it a vulnerability or security threat. 

This is expected at times as a part of using Console Ninja. This is explained in the link we provide in the comment at the top of these files: [https://github.com/wallabyjs/console-ninja#how-does-it-work](https://github.com/wallabyjs/console-ninja#how-does-it-work).

Unless build artefacts are being committed while Console Ninja is active, this should not be happening. In our docs, we recommend that Console Ninja is paused before running a build. We also explicitly disable Console Ninja in cases where we detect a production build. 

We will investigate why these files included Console Ninja artefacts for the projects listed in your GitHub search.

**Comment by smcenlly** [comment]
We've investigated all of the samples that were linked in the Github search.

Many of these were expected as a result of people committing development mode artefacts (e.g. as a result of not correctly configuring .`gitignore`).

We found two situations where Console Ninja did not know about production mode of tools. This affected the latest version of Angular (v17) using esbuild, and with vanilla webpack configurations (i.e. outside of any specific tools / frameworks). Both of these issues have been fixed in the latest version of Console Ninja (`v1.0.317`).

We will keep an eye on the results of your search query to handle these cases better where we can.
