### ISSUE TITLE
[Feature]: Support for Create Figma Plugin

### ISSUE THREAD

**Issue by artivilla** [wallabyjs/console-ninja#312]
### Describe the feature you'd like.

I'm guessing Create Figma Plugin is using a custom build tool. Would love for this to be supported as its the go to figma plugin builder. https://yuanqing.github.io/create-figma-plugin/

**Comment by mburnell** [comment]
We've taken a look at `Create Figma Plugin`, and unfortunately there are two different reasons Console Ninja does not support it at this time.

First, in order to run, Console Ninja must be able to intercept file-read operations to perform its processing and add its instrumentation logic. `Create Figma Plugin` uses `esbuild` (specifically `esbuild.build`), which runs in a separate process outside of the Javascript runtime, and currently does not provide a way to incercept the required operations.

Second, it appears the model here is to build your plugin and deploy it to Figma, which acts as the runtime for the plugin. Ninja currently has no way to integrate with this environment. If not for the build issues described above, it might be possible to leave instrumentation artefacts in the build output (usually undesired), but even then, because of the disconnect in life cycle, it would be difficult to push logs back to Ninja. We don't currently have plans to support scenarios such as this.

**Comment by artivilla** [comment]
All good. I didn't know what the complexity was under the hood, I simply think it would be useful to have the same DX as when building apps. If you know a workout that would be neat but if not, I'll stick to console logs. :) 
either way, happy console ninja user so TY!
