### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by feernandobraga** [wallabyjs/console-ninja#333]
### What happened?

I can't get anything logged into vscode. The icon remains as a watch that reads:

Console Ninja is  waiting for runtime events. Console Ninja has started with next.js and is now waiting for some runtime logs or errors.

### Version

v1.0.350

### CLI command to start your dev tool

pnpm run dev

### Steps to reproduce (or sample repo)

This is just a simple next app, only edited to add a button that is binded to console log function

https://github.com/feernandobraga/console-ninja-troubleshoot

### Log output

```shell
21:08:45.100 info buildHook-13324 installing build hook for next.js at c:\users\fernandobraga\console-ninja, node v20.12.2
21:08:45.107 info buildHook-13324 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, live-server-extension, live-preview-extension, node
21:08:45.107 info buildHook-13324 running tools: next.js
21:08:45.111 info buildHook-13324 installing fs interceptor
21:08:45.161 info host client connected: buildHook { address: '127.0.0.1', family: 'IPv4', port: 55765 }
21:08:45.166 ERR! host Invalid pointer at 0x3C9D.
21:08:45.190 info buildHook-13324 file processed (stat): 1 log points, error handler: false, network logging handler: false
21:08:45.191 info buildHook-13324 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, live-server-extension, live-preview-extension, node
21:08:45.191 info buildHook-13324 running tools: next.js
21:08:45.194 ERR! host Invalid pointer at 0x3C9D.
21:08:45.697 info buildHook-20148 installing build hook for next.js at c:\users\fernandobraga\console-ninja, node v20.12.2
21:08:45.703 info buildHook-20148 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, live-server-extension, live-preview-extension, node
21:08:45.704 info buildHook-20148 running tools: next.js
21:08:45.706 info buildHook-20148 installing fs interceptor
21:08:45.742 info host client connected: buildHook { address: '127.0.0.1', family: 'IPv4', port: 55765 }
21:08:45.772 info buildHook-20148 file processed (stat): 1 log points, error handler: false, network logging handler: false
21:08:45.772 info buildHook-20148 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, live-server-extension, live-preview-extension, node
21:08:45.772 info buildHook-20148 running tools: next.js
21:08:45.776 ERR! host Invalid pointer at 0x3C9D.
21:08:45.777 ERR! host Invalid pointer at 0x3C9D.
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. There was a compatibility issue with Console Ninja for the latest versions of next.js, which was affecting your project.

If you are using Console Ninja PRO edition, `next.js@14.2.6` priority access is available from version Console Ninja `v1.0.351`; please update the extension and it will fix your problem.

If you are using Console Ninja Community edition, the release date for `next.js@14.2.6` support will be around 21st October, 2024. Please note that Community Edition includes free access to thoroughly tested integration with Node.js and supported tools (such as next.js) and is usually available ~2 months after new versions of supported tools are released. This timeline ensures each version's stability and robust support, minimizing potential issues so that we can provide a dependable experience to community users with minimal effort on our part.
