### ISSUE TITLE
[Feat]: vite v5.4.2 support for Community Edition

### ISSUE THREAD

**Issue by moominshera** [wallabyjs/console-ninja#335]
### What happened?

Just fix this supporting issue as console ninja isn't working in vite version 5.4.2

### Version

v1.0.351

### CLI command to start your dev tool

pnpm dev or npm run dev 

### Steps to reproduce (or sample repo)

pnpm dev or npm run dev 

### Log output

```shell
pnpm dev or npm run dev
```

**Comment by smcenlly** [comment]
We're assuming that you're using Console Ninja Community Edition. For Community edition, the release date for vite@5.4.2 support will be around 20th October, 2024. You should see this displayed via a message in your console where you run `npm run dev`.

Please note that Community Edition includes free access to thoroughly tested integration with Node.js and supported tools (such as vite) and is usually available ~2 months after new versions of supported tools are released. This timeline ensures each version's stability and robust support, minimizing potential issues so that we can provide a dependable experience to community users with minimal effort on our part.

For those using Console Ninja PRO edition, vite@5.4.2 priority access is already available.

**Comment by idealprojectuz** [comment]
✘ vite v5.4.9 is not yet supported in the Community edition of Console Ninja.
We are working hard on it for you https://tinyurl.com/3h9mtwra.

**Comment by smcenlly** [comment]
Please refer to our reply above: https://github.com/wallabyjs/console-ninja/issues/335#issuecomment-2327577906
