### ISSUE TITLE
Request to Publish Extension on open-vsx.org

### ISSUE THREAD

**Issue by Suryachandra-DTH** [wallabyjs/console-ninja#346]
### Describe the feature you'd like.

Hello,
Thank you for developing the console-ninja extension. I noticed that the extension is available on the Microsoft Marketplace but not on [open-vsx.org](http://open-vsx.org/), which is an open-source alternative that serves the broader community, including VSCodium users.
Would you consider publishing your extension on [open-vsx.org](http://open-vsx.org/) as well? It would benefit users who prefer or are required to use open-source software. The process is outlined here: [Publishing Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).
Thank you for considering this request.
Regards,
Surya

**Comment by smcenlly** [comment]
Unfortunately the [Open VSX marketplace agreement](https://open-vsx.org/publisher-agreement-v1.0) is not compatible with our licensing model because of our PRO offering. It's not possible for us to ship Console Ninja Community Edition separately for just the Open VSX marketplace.

> **3.e. No Compensation​.** You expressly acknowledge that neither Eclipse nor any licensee or end-user of any of your Offerings published on the Registry shall be required to provide you with any compensation for the distribution or use of your Offering as made available on the Registry.

We do not have any plans to publish Console Ninja to the Open VSX marketplace, but you are fully able to use all of our products with VSCodium today:

To use Console Ninja, Wallaby, or Quokka you will need to download the extension from the Microsoft marketplace and then install from VSIX:

- [Marketplace for Console Ninja](https://marketplace.visualstudio.com/items?itemName=WallabyJs.console-ninja)
- [Marketplace for Wallaby](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode)
- [Marketplace for Quokka](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)
