### ISSUE TITLE
Log details are no longer available. 

### ISSUE THREAD

**Issue by Kamlesh502** [wallabyjs/console-ninja#49]
I am using console ninja in react project. it shows the console log in inline as well as in new file but not able to see the full object if the output object is too big if i try to expand the object it shows logs details are no longer available 
<img width="516" alt="Screenshot 2022-12-14 at 12 35 01 AM" src="https://user-images.githubusercontent.com/25546153/207423051-c856f8fc-83aa-48c0-b532-d43615431ee1.png">
<img width="569" alt="Screenshot 2022-12-14 at 12 36 04 AM" src="https://user-images.githubusercontent.com/25546153/207423063-4ef82366-0b8c-4250-be75-34d4057f7629.png">

**Comment by ArtemGovorov** [comment]
Can you please attach your `~/.console-ninja/trace.log` file?

**Comment by smcenlly** [comment]
We fixed a problem yesterday that exhibited the same way that you are describing. The problem was fixed in Console Ninja, `v0.0.33`.

Can you please confirm that you are using the latest version of Console Ninja, and if you're still having the problem, please attach the `trace.log` file as requested by @ArtemGovorov.

**Comment by Kamlesh502** [comment]
thanks @smcenlly  @ArtemGovorov  the issue is resolved now !
