### ISSUE TITLE
The displayed time format should be aligned with client's timezone

### ISSUE THREAD

**Issue by rwu823** [wallabyjs/console-ninja#50]
The current display should be the time zone of +00 Is it possible to align clients?

**Comment by smcenlly** [comment]
The date/time is always displayed in local time (by design). Unlike when you may be looking at server-side logs, we had figured it would make sense that you're looking at the time in local time zone vs. having to do unnecessary time-zone conversion in your head while looking at the logs.

The time-zone component is therefore not relevant (and just takes up visual real-estate).

Does that help / answer your question? If it's not working for you or doesn't make sense, can you please provide additional context of what you're seeing and what you're expecting to see?

**Comment by rwu823** [comment]
@smcenlly Yes, I mistake between `hh` and `HH`. Thanks for explaining.
