### ISSUE TITLE
"Waiting for Jest to start"

### ISSUE THREAD

**Issue by meatnordrink** [wallabyjs/console-ninja#51]
I realize this may just be me not understanding the documentation, but in hopes that it might lead to an answer in the documentation that might help others - 

The extension status is: 

```
Console Ninja is ⌛ waiting for jest to start. Console Ninja has successfully integrated with jest found in your project dependencies, but has not connected to a running instance of it yet.

What to do next
You may now start/restart jest.
```

Two questions - 
1. Why do I need to start Jest, to get console errors? 
2. I started Jest (I ran the unit tests for this repo), and still no luck. Does it mean "start jest" in some other way?

Excited for this tool, and to recommend it to my colleagues - but want to get it working first! :joy:

**Comment by smcenlly** [comment]
Can you please tell us a little about your project and what technologies you are using?

When Console Ninja detects your project, it looks for various technologies that are supported and then will display a message that tells you want to do to start seeing `console.log` statements.

If you only see a message, `You may now start/restart jest.` that means that `jest` is the only technology that Console Ninja detected.

If you add `console.log("Hello World");` to one of your test files or source files that are executed when you run `jest` from the CLI, you should see the console log value.

Right now, Console Ninja only supports `console.log` statements in `jest`, this is because test errors are caught/handled by test runners themselves, and special processing is required to format and display test results. You may be interested in trying one of our other products, [Wallaby.js](https://wallabyjs.com), if you want a more comprehensive experience executing tests from your editor.

---

If it's not working for you as described above, please provide us with more details about your project:

1. `package.json`
2. the script or CLI command you use to run `jest` from the CLI

**Comment by meatnordrink** [comment]
@smcenlly , thank you so much for the detailed and thoughtful reply! 

> If you add console.log("Hello World"); to one of your test files or source files that are executed when you run jest from the CLI, you should see the console log value.

That's not working, but I wonder if Ninja is just having trouble with my setup. I have all our repos in a single VSCode workspace, and I'm noticing that, whichever repo a file I open is in, the message from Console Ninja is the same. (I wouldn't be surprised if it had trouble with our main repo, which is a manual SSR webpack setup; but it doesn't do any better with one of our newer CRA repos.)

I'll have to check if it's cool if we copy out `package.json` publicly - I have no idea. We run Jest with 
```
jest --watchAll
```
prepended with `crossEnv` and a bunch of environment variables. 

I'm happy to close this, though - I thought I'd take a quick shot, but I don't really have time to allocate to it, nor do I wish to waste your time with figuring out how to get it to work with our specific setup. 

Thank you!!

**Comment by ArtemGovorov** [comment]
@meatnordrink Thanks for your reply. We'll need some more details from you to understand why it's not working, but as you've indicated you can't allocate more time on it, so I'm going to close the issue for now. 

Having said that, we'd love to understand why it's not working for your setup. From what you've described so far, your setup should be supported and should just work. So if you have some time in future to provide us with some more info, we are happy to re-open the issue and take it from there.

**Comment by meatnordrink** [comment]
Thank you! If I find some more time to mess with it in the future, I'll re-open this.
