### ISSUE TITLE
Lost the ability to console.log

### ISSUE THREAD

**Issue by jpwallace22** [wallabyjs/console-ninja#58]
Using version `v0.0.45` I lost the ability to `console.log()` top level in a NextJS environment when I uninstalled the extension. The only way I can `console.log()` is in the JSX return. This is a NextJS environment with Typescript.

The bug only exists AFTER uninstalling. 

I cant use the extension because it crashes with the latest version of Next, and not I cant remove it because it removes my ability console.log

**Comment by ArtemGovorov** [comment]
> Using version v0.0.45 I lost the ability to console.log() top level in a NextJS environment.

Do you mean you add console.log and it doesn't print any results, or it produces some side effects, like in the other issue that you have created: https://github.com/wallabyjs/console-ninja/issues/54?

Can you please share 
- node.js version
- next.js version?

> The bug persists AFTER uninstalling

After pausing/uninstalling the extension, try stopping next.js, then deleting cache folders: `rm -rf node_modules/.cache` and `rm -rf .next`, and then restart next.js. If the issue is Console Ninja related, it should help.

**Comment by jpwallace22** [comment]
@ArtemGovorov Thank you for getting back quickly, as I'm sure you can understand losing the ability to console.log as been inconvenient to say the least.

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.7-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

It doesn't log any output at all to my dev tools console within google chrome if the console.log is within the top-level of the function. The other issue (#54) is the reason that I uninstalled it. Which led to this new issue. 

I tried `rm -rf node_modules/.cache` and `rm -rf .next` immediately. No joy.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the details.

```
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 6.11.0
```

Which package manager of those 3 are you using for the project?

> It doesn't log any output at all to my dev tools console within google chrome if the console.log is within the top-level of the 
function

Oh, if there's no output in chrome dev tools, then the issue is likely related to the Console Ninja extension, especially when it's uninstalled and with caches cleared. 

To eliminate any possibility of previously installed extension processes somehow being orphaned and still running (unlikely, but still), can you please:
- restart your machine,
- clone your repo in a fresh directory,
- run `npm i`, start next.js and try logging.

If the issue persists even after those steps, it's most certainly not related to the extension.

**Comment by jpwallace22** [comment]
I am using `yarn` for this one

> To eliminate any possibility of previously installed extension processes somehow being orphaned and still running (unlikely, but still), can you please: 

I tried all of those. And it still didn't work. When I reinstall Console Ninja, I regain the ability to console.log() and see it within the chrome dev tools. As soon as I uninstall it, it goes away.

**Comment by ArtemGovorov** [comment]
Very puzzling, can't think of a way how exactly the extension (when **uninstalled**) can cause the logs to disappear from Chrome dev tools.

Try this:
- after pausing/uninstalling the extension, stop next.js, run `rm -rf node_modules/.cache` and `rm -rf .next`,
- start next.js, add new `console.log` to the place where it's not working anymore but is definitely expected to - root of your index.ts/Home component.
- open Chrome Dev Tools, Sources Tab, find the file with the console.log (should be under `webpack-internal://`), put a breakpoint on the line with the log:
![cn2gif](https://user-images.githubusercontent.com/979966/208203187-d12f6c87-abed-4f8b-b670-7ea247d84a8b.gif)
- refresh the browser page to see if the log is hit.

**Comment by jpwallace22** [comment]
It's not even making it to the browser. 

This is from the source code:
![Screen Shot 2022-12-16 at 3 25 55 PM](https://user-images.githubusercontent.com/93415734/208204818-cb06fe0a-f661-4502-ac3a-e53aed66183a.png)


And this is from the dev tools: 

![Screen Shot 2022-12-16 at 3 26 13 PM](https://user-images.githubusercontent.com/93415734/208204872-7d671e97-190c-48f6-9264-0cb6d5819b6a.png)

**Comment by ArtemGovorov** [comment]
Hmm, it looks like something is replacing console.log with `_s();`. Console Ninja is not doing this replacement (our replacement is very different).

Can you please share the full content of the source when taken from Dev Tools, or check yourself where the `_s()` defined/imported from in the file? Maybe still put a breakpoint on the `_s();` line and step into it under the debugger running to see where it leads?

**Comment by jpwallace22** [comment]
https://user-images.githubusercontent.com/93415734/208208498-11e0122d-29e2-4e58-88b2-7a29bb831fa7.mov

@ArtemGovorov

**Comment by ArtemGovorov** [comment]
Thanks, I can see from the video the `_s` is defined on line 24 of the source file is dev tools and it says: `var _s = $RefreshSig$()`. [Google-ing it](https://www.google.com/search?{google:acceptedSuggestion}oq=%24RefreshSig%24&{google:instantFieldTrialGroupParameter}sourceid=chrome&ie=UTF-8&q=%24RefreshSig%24) points to some react hot reload webpack related transformations. The code transform is not related to the extension, it maybe related to something else in your setup/environment. 

The reason it starts working when you install Console Ninja, is because the extension changes `console.log` to something like `(cnFunc(), console.log(...))`, and I think this change from a statement to a sequence expression statement makes that react hot reload webpack related transformation that breaks your logs not touch the code, and that's why the log starts working with console ninja.

**Comment by jpwallace22** [comment]
@ArtemGovorov  I removed the console log and the _s() is still there. It is completely related to the console log from the source code. It's just part of the fast refresh for dev

**Comment by ArtemGovorov** [comment]
> I moved the console.log to a different part of the file and it didn't move with it. It just never appears.
Ok, looks like something is removing it, not sure what is doing it though.

We are happy to investigate and help even if the issue is completely unrelated to the extension. If you can share a sample project repo (could be a copy of your real project with nothing but the Home file without any dependencies) and it the issue can still be reproduced there, I'm confident we can find the exact reason of why it's happening.

**Comment by jpwallace22** [comment]
@ArtemGovorov  The whole project is public on my Github at https://github.com/jpwallace22/portfolio, does that help?

**Comment by ArtemGovorov** [comment]
Thanks for sharing the project. Tried it and `console.log` is working for me in the project (with and without console ninja):

![cn2gif](https://user-images.githubusercontent.com/979966/208214002-3c366f9a-3a1c-4389-a6dc-3ecd3326e4b9.gif)

**Comment by jpwallace22** [comment]
@ArtemGovorov Have you tried removing Console Ninja? 

This is the only repo I used console ninja in and the only repo that console logging doesn't work in.

**Comment by ArtemGovorov** [comment]
Yes, have just tried a few scenarios :
- tried with Ninja on;
- tried with paused Ninja w/o and with restarting editor (all instances) after pause;
- tried uninstalled Ninja w/o and with restarting editor (all instances) after uninstall.

Probably not related, but one thing I have noticed is in your project that eslint is complaining about `console.log`:

<img width="629" alt="Screen Shot 2022-12-17 at 10 56 15 am" src="https://user-images.githubusercontent.com/979966/208214664-2fd0a807-4016-41bd-9af5-016136ba0304.png">

It doesn't look like the rule violation is being enforced on the code transform level (at least not for me), but wondering maybe  there's something else in your setup that I'm missing that is actually enforcing the rule and removing those logs during code transforms?

**Comment by jpwallace22** [comment]
The linting is just a warning to make sure I don't leave it in there. It shouldn't (and doesn't in other repos) effect anything other than showing a squiggly line.

**Comment by ArtemGovorov** [comment]
One easy way to make sure Console Ninja didn't touch the file is that to verify if there's no special function called `oo_oo` being appended at the end of the file:
![cn2gif](https://user-images.githubusercontent.com/979966/208215364-bb1dd25e-50d9-4e9c-a4ec-ae134981299d.gif)

When console ninja runs, it transforms console.log to prefix it with the special function call and adds that special function at the end of the file. Can you please verify that the function is not there in dev tools source when `console.log` disappears?

One last thing I can think of is to completely delete Console Ninja related files from the machine after uninstall (to make everything just like the tool has never been installed). After uninstalling it, try this:
- go to `~/.vscode/extensions/` and manually delete any folders with `console-ninja` substring (VS Code is supposed to be lazily doing it at some point)
- delete `~/.console-ninja` folder
- restart editor, next.js and try.

**Comment by jpwallace22** [comment]
I verified. Nothing at the bottom of the page.

I also deleted everything from the extensions directory at my root. And restarted everything. Still no joy.

**Comment by ArtemGovorov** [comment]
We have done more investigation and have found what is causing the issue.

Last week you have made [the following change](https://github.com/jpwallace22/portfolio/blob/ca3f728def64ffbdfa10430e489a3e25a572b751/next.config.js#L12) to your `next.config.js`:

```js
module.exports = withBundleAnalyzer({
  images: {
    domains: ['localhost', 'justinwallace.dev', 'www.datocms-assets.com'],
  },
  compiler: {
    styledComponents: true,
    removeConsole: true, // <---- this one
  },
```

and the change is exactly what's causing the issue.  

As we've been suspecting, the issue has nothing to do with Console Ninja (as a matter for fact for the reason [described here](https://github.com/wallabyjs/console-ninja/issues/58#issuecomment-1355845265)) Console Ninja was giving you your `console.log`-s back despite the change.

Please remove the setting and it should work for you. We hope it helps and hopefully at some point you may give Console Ninja another go (at this point we can't reproduce https://github.com/wallabyjs/console-ninja/issues/54 and it also may be related to your recent changes rather than to Console Ninja).

We would also appreciate if you consider updating your [recent negative review](https://marketplace.visualstudio.com/items?itemName=WallabyJs.console-ninja&ssr=false#review-details) on the tool's page, as your comment there is blaming the tool and can be misleading for other users.

**Comment by jpwallace22** [comment]
@ArtemGovorov I have literally no idea how that got in there.I think I would remember adding something like that to my own config. That's insane. However, I did, and that WAS the problem. 
I will correct my review to reflect the great support I received on this ticket. Thank you.

**Comment by ArtemGovorov** [comment]
Awesome, thank you!
