### ISSUE TITLE
Extension causing Next.js compilation to fail under some conditions

### ISSUE THREAD

**Issue by TrevorBurnham** [wallabyjs/console-ninja#59]
I was working on a Next.js project today and noticed a strange issue: Any time I have multiple styled-components `styled` declarations in the same module and any `console.log` statement, compilation fails (in development mode only) with this error:

```
Module parse failed: Identifier '_templateObject' has already been declared (11:9)
File was processed with these loaders:
 * ./node_modules/next/dist/compiled/@next/react-refresh-utils/dist/loader.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
|     return data;
| }
> function _templateObject() {
|     const data = _tagged_template_literal([
|         ""
Hello world!
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

(The `Hello world!` is the output from the `console.log` statement, which seems notable: Somehow the `console.log` was executed even though the module that contains it couldn't be parsed!)

I wrote up precise steps to replicate at https://github.com/vercel/next.js/issues/44113, before I put 2 and 2 together and realized that the extension was responsible for the error.

I also found one other report of the same issue (with Emotion instead of styled-components) here: https://stackoverflow.com/questions/74834358/module-parse-failed-identifier-templateobject-has-already-been-declared/74838206.

I'm running Consola Ninja v0.0.45.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo, it was very helpful.

While the issue in this case was caused by Console Ninja, it's not specific to it. If you add simple `eval("");` anywhere in your component code, you'll get the same error with Console Ninja paused or even uninstalled. Console Ninja add some code that contains `eval`, and that's why it was breaking.

It looks like an issue with swc loader, so if you like you may still re-open your issue in next.js repo with a small correction.

Anyway, we have wrapped our `eval` call into something that doesn't break swc loader anymore. Please update Console Ninja to v0.0.46 and it should work.

**Comment by TrevorBurnham** [comment]
Thanks! I appreciate the quick turnaround. I've reopened the Next.js issue for further investigation.
