### ISSUE TITLE
[Feature]: Support vscode-jest extension

### ISSUE THREAD

**Issue by svekl** [wallabyjs/console-ninja#69]
### Describe the feature you'd like.

Hi, 

First of all thank you for this awesome extension!

And it could become even better if it supported popular `vscode-jest` extension https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest
I love to run individual tests via `vscode-jest`  and if Console Ninja could show their console calls - it could save even more time.

**Comment by smcenlly** [comment]
Thanks for your feature request. 

We do not plan to further extend our integration with test runners.

While you may use Console Ninja to display logs from supported test runner CLIs, test errors and test execution logic are not handled by Console Ninja; this is because test errors are caught/handled by test runners themselves, and special processing is required to know about test execution and to format and display test results.

---

Having said that, you may be interested to checkout [Wallaby.js](https://wallabyjs.com/),  another tool from our team. Wallaby.js runs your JavaScript and TypeScript tests immediately as you type, highlighting results in your IDE right next to your code. Wallaby.js was the [inspiration for `vscode-jest`](
https://github.com/jest-community/vscode-jest/blob/aefe66ee82a62a36f0b156b453e009a5237e5922/README.md#inspiration). Wallaby.js console output is like Console Ninja on steroids.

Wallaby not only displays logs and test errors inline (and in a separate ergonomically designed view), but is also [packed with features](https://wallabyjs.com/#features), such as inline code coverage and a time travel debugger, that provide superpowers to your current testing framework/stack, such as [Jest, Vitest, Mocha. etc.](https://wallabyjs.com/#tools)

Wallaby is free for open source projects and has a paid version for closed-source projects (a free 15 day trial is available).
