### ISSUE TITLE
Mangled source code

### ISSUE THREAD

**Issue by samdenty** [wallabyjs/console-ninja#70]
### What happened?

<img width="1347" alt="CleanShot 2022-12-23 at 18 32 45@2x" src="https://user-images.githubusercontent.com/13242392/209392271-a1201a32-22bb-40a4-bdb0-06a82a7810e7.png">

### Version

1.0.0

### Steps to reproduce (or sample repo)

I was running my app in the browser, and console.logged a value, it had a `VM` stack trace without any file. I clicked the stack trace and it showed a obfuscator javascript file. As this was obfuscated, I first thought I had a malicious node_module installed that was somehow running on the page.

I didn't see console_ninja immediately in the file, but instead saw WebSocket which made me think it's nefarious.

Does this file really need to be mangled? Or at least, mention console ninja somewhere at the top

### Log output

```shell
-
```

**Comment by smcenlly** [comment]
> Does this file really need to be mangled? 

Yes - we need to do this to protect our IP. While not ideal, it's an unfortunate reality that people steal the work of others.

> Or at least, mention console ninja somewhere at the top

Great idea. Thanks for the suggestion.

**Comment by samdenty** [comment]
It's an awesome product!

**Comment by DieterHolvoet** [comment]
Obfuscating JS is a very shady practice, especially since there isn't any source code for users to audit. For all we know this code could be collecting confidential information and sending it to third parties.

**Comment by samdenty** [comment]
I don't see a problem with mangling the vscode extension server bit, but maybe not anything that's being served to the end-user.

as I agree with @DieterHolvoet, my first thought was that it was malicious

**Comment by ArtemGovorov** [comment]
> Or at least, mention console ninja somewhere at the top

Maybe let's add the link to our docs https://github.com/wallabyjs/console-ninja#how-does-it-work to the generated runtime code. The docs section describes in detail how the tool works, what code is injected in runtime and what it's doing.

**Comment by ArtemGovorov** [comment]
We have added [the link to our docs](https://github.com/wallabyjs/console-ninja#how-does-it-work) to the injected obfuscated code. The docs explain in detail what the code is doing and should hopefully address the issue to some extent.

While we agree that the solution is not ideal and the code can't be audited, many VS Code extensions minify their code (thus also making it harder to audit). The reality is that even non obfuscated code is not being audited by the vast majority of users, as it's practically impossible to manually inspect each and every commit in each and every used extension. Obviously, apart from VS Code extensions, a typical software developer uses a lot of other tools (local and cloud based) that have access to user's private data and have no source code available for auditing by end users.

This makes the issue to be more about trusting the publisher/vendor rather than about anything else. And to address the trust part of the issue a bit further, it's worth mentioning that [as a company we've been in the dev tools business since 2015](https://wallabyjs.com/about/), producing multiple tools trusted by hundreds of thousands software developers around the world. You may also check out [our privacy policy](https://wallabyjs.com/privacy/).
