### ISSUE TITLE
[Bug]: Console log error websocket connection

### ISSUE THREAD

**Issue by wilkensgomes** [wallabyjs/console-ninja#71]
### What happened?

![Captura de tela_20221223_214616](https://user-images.githubusercontent.com/38788876/209415831-754714e7-bc26-4fdf-a9ca-dfd78c61c146.png)

### Version

0.0.54

### Steps to reproduce (or sample repo)

The error persists in appearing in the Chrome console even after uninstalling the extension, how to remove it?

### Log output

```shell
WebSocket connection to 'ws://127.0.0.1:63130/' failed
```

**Comment by ArtemGovorov** [comment]
Can you please provide some more details about your stack (ie. is it Vite, CRA, Next.js, something else; also package manager that you're using npm/yarn/pnpm). The error itself should be harmless and can be ignored (or even filtered in dev tools). The issue is related to your tool cache (being modified after using Console Ninja). Depending on the used tech, here's what should help to get rid of it (invalidate cache):
- `rm -rf node_modules/.cache/`
- `rm -rf node_modules` and `npm i`
- touch your `index.html` file (and/or file(s) where you have `console.log` statements).

We'll be looking into making sure the issue doesn't happen as a part of https://github.com/wallabyjs/console-ninja/issues/9.

**Comment by productdevbook** [comment]
same problem how to change `127.0.0.1` hostname ?
