### ISSUE TITLE
[Feature]: Log other object properties including functions

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#83]
### Describe the feature you'd like.

I tried console logging the props coming from a rest paramater and I thought that it is an empty object but turns out there are functions included which is I don't see on the console ninja. But is present on the Chrome Dev tools console tab. 

So I have a CustomSwitch component with a register function (from the react-hook-form library)  that returns an object which includes some event handler functions. 

Although I'm not sure what the functions being returned are

![image](https://user-images.githubusercontent.com/65213312/211940156-2db9454f-d4ea-4b0c-bf9f-9173c50d5149.png)

 so I tried to console log it with Console Ninja but it shows an empty object inside the Custom Switch that's why I thought there's something wrong with the react-hook-form libary or the way that I've used it. 
 
  
![image](https://user-images.githubusercontent.com/65213312/211940632-bca064e3-7333-4d16-a5da-2dff60287dcb.png)

But in the console tab of the Chrome Dev tool it is showing the functions inside the "rest" object.  

![image](https://user-images.githubusercontent.com/65213312/211940806-8451548e-3853-42ff-bbb9-a45d615c2be8.png)

Can you also please add the functions inside of the object when console logging using Ninja? I think this is good for debugging use cases. Thanks

**Comment by ArtemGovorov** [comment]
We have excluded function names from logged output by design as they may take a lot of output realestate while typically providing low informational value to users (comparing to other properties with data).

Having said that, as you have pointed out, sometimes function names may be useful to see in the output. We have added the new "Capture Functions" setting in the latest v0.0.63+ to output function names in logged objects:

<img width="944" alt="Screen Shot 2023-01-12 at 11 58 51 am" src="https://user-images.githubusercontent.com/979966/211957820-f74b165a-8526-4d43-9ec0-b73e72874454.png">

<img width="715" alt="Screen Shot 2023-01-12 at 11 58 09 am" src="https://user-images.githubusercontent.com/979966/211957881-726878bf-36fc-467a-96d9-43109b584369.png">

**Comment by omerson-cruz** [comment]
Awesome!  You guys are really great. Thank you so much for this feature.
