### ISSUE TITLE
[Feature]: Qwik Support

### ISSUE THREAD

**Issue by snips-dev** [wallabyjs/console-ninja#93]
### Describe the feature you'd like.

Should be great having a Qwik framework support.

**Comment by smcenlly** [comment]
Just want to confirm, I assume you're referring to: https://qwik.builder.io?

**Comment by EamonHeffernan** [comment]
> Just want to confirm, I assume you're referring to: https://qwik.builder.io?

I'd assume they are. Just to give some background on why it currently doesn't work, although Qwik uses Vite, Qwik requires all called functions to be inside what are called QRL scopes. This tells Qwik how to split code into individual chunks to be sent separately. The error that shows up when trying to use console.log in Qwik is `Reference to identifier declared at the root 'oo_oo'. It needs to be exported in order to be used inside a Qrl($) scope.`

**Comment by EamonHeffernan** [comment]
Doing something like this works, however the logs show up on the line in this function, as would be expected.
```
export const log = (message?: any, ...optionalParams: any[]) => {
	console.log(message, ...optionalParams);
};
```

**Comment by EamonHeffernan** [comment]
> Doing something like this works, however the logs show up on the line in this function, as would be expected.
> 
> ```
> export const log = (message?: any, ...optionalParams: any[]) => {
> 	console.log(message, ...optionalParams);
> };
> ```

I've managed to get it working as would be expected by replacing `function oo_oo` with `export function oo_oo` in the output from console-ninja

**Comment by EamonHeffernan** [comment]
@smcenlly Hi, I just wanted to draw your attention to this issue if you had not seen it.

**Comment by smcenlly** [comment]
Thanks for letting us know how you go it working. 

Console Ninja `v0.0.75+` now supports Qwik framework.
